<?php

namespace App\Models\ISO_B2B;

use Illuminate\Database\Eloquent\Model;

class OrderNote extends Model
{
    protected $fillable = [
        'order_id',
        'user_id',
        'status',
        'note',
    ];

    public function order()
    {
        return $this->belongsTo(Order::class);
    }

    public function user()
    {
        return $this->belongsTo(\App\Models\User::class); // User model is usually outside ISO_B2B
    }

    /**
     * Notes are generated by trusted server code and legitimately contain
     * formatting HTML (<br>, <strong>, bullet lists), but may also embed a
     * user-supplied reason. This accessor renders the safe formatting tags
     * while stripping scripts, styles, and any tag attributes (e.g. onclick),
     * so the frontend can output it with {!! $note->safe_html !!} safely.
     */
    public function getSafeHtmlAttribute(): string
    {
        $raw = $this->note;

        if ($raw === null || $raw === '') {
            return '';
        }

        // 1. Drop <script>/<style> blocks entirely (tags + their content).
        $clean = preg_replace('#<(script|style)\b[^>]*>.*?</\1>#is', '', $raw);

        // 2. Keep only a safe whitelist of formatting tags.
        $clean = strip_tags($clean, '<br><b><strong><i><em><u><ul><ol><li><p><span>');

        // 3. Strip any attributes left on those tags (neutralises onclick=, etc.).
        $clean = preg_replace('/<(\/?)(br|b|strong|i|em|u|ul|ol|li|p|span)\b[^>]*>/i', '<$1$2>', $clean);

        // 4. If the note carries no <br> at all, honour raw newlines as breaks.
        if (stripos($clean, '<br') === false) {
            $clean = nl2br($clean, false);
        }

        return $clean;
    }
}
